ovh-ux/ovh-ui-angular

bower.json, package.json
=> chore(*): version 1.1.1

package.json, packages/oui-angular/src/index.js, packages/oui-tooltip/README.md, packages/oui-tooltip/src/index.js, packages/oui-tooltip/src/index.spec.js, packages/oui-tooltip/src/tooltip.controller.js, packages/oui-tooltip/src/tooltip.directive.js, packages/oui-tooltip/src/tooltip.html
UU-519 (linked to https://github.com/ovh-ux/ovh-ui-kit/pull/104)
Preview http://temp_oui_tooltip.ui-kit.ovh
=> feat(oui-tooltip): add oui-tooltip component

package.json
=> fix(package): ovh-ui-kit peer dependency version

packages/oui-numeric/src/numeric.html
replace wrong accessiblity attributes
http://angular_fix_oui_numeric_accessibility.ui-kit.ovh/#!/oui-angular/numeric
=> fix(oui-numeric): fix accessibility attributes.

packages/common/test-utils.js, packages/oui-checkbox/README.md, packages/oui-checkbox/src/checkbox.component.js, packages/oui-checkbox/src/checkbox.html, packages/oui-checkbox/src/index.spec.js
http://angular_feat_checkbox_description.ui-kit.ovh/#!/oui-angular/checkbox
=> feat(oui-checkbox): description attribute

packages/oui-dropdown/src/dropdown-trigger.directive.js, packages/oui-dropdown/src/dropdown.controller.js
http://angular_uu_551_fix_esc_dropdown.ui-kit.ovh/#!/oui-angular/action-menu
=> UU-551 - Escape button does not close the action menu

packages/oui-action-menu/src/action-menu.controller.js, packages/oui-action-menu/src/action-menu.html, packages/oui-dropdown/src/dropdown.controller.js
Fixes UU-582
http://angular_uu_582_action_menu_in_datagrid.ui-kit.ovh/#!/oui-angular/action-menu
=> fix(actionMenu): fix action menu positioning

.editorconfig
=> fix(editorconfig): fix indentation value

packages/common/test-utils.js, packages/oui-checkbox/src/checkbox.html, packages/oui-checkbox/src/index.spec.js
http://input_height_staging.ui-kit.ovh/#!/oui-angular/checkbox
=> fix(oui-checkbox): element structure

packages/oui-tooltip/src/tooltip.html
UU-558
Linked to https://github.com/ovh-ux/ovh-ui-kit/pull/113
Staging: http://build_oui_tooltip.ui-kit.ovh/#!/oui-angular/tooltip
=> style(oui-tooltip): update oui-tooltip to specs

packages/oui-datagrid/src/index.js, packages/oui-datagrid/src/table-column-builder.service.js, packages/oui-datagrid/src/table.controller.js, packages/oui-datagrid/src/table.directive.js
=> refactor(oui-datagrid): extract column builder

packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/index.js, packages/oui-datagrid/src/paging/datagrid-local-paging.js, packages/oui-datagrid/src/paging/datagrid-paging-abstract.js, packages/oui-datagrid/src/paging/datagrid-paging.service.js, packages/oui-datagrid/src/paging/datagrid-remote-paging.js
Demo: http://refactor_paging_service_staging.ui-kit.ovh/#!/oui-angular/datagrid
I will do another pass to remove unused parameters in DatagridController constructor.
=> refactor(oui-datagrid): new paging service

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-dropdown/src/dropdown.controller.js, packages/oui-pagination/README.md, packages/oui-pagination/src/index.js, packages/oui-pagination/src/index.spec.js, packages/oui-pagination/src/pagination.component.js, packages/oui-pagination/src/pagination.controller.js, packages/oui-pagination/src/pagination.html, packages/oui-pagination/src/pagination.provider.js
=> feat(pagination): add new component

packages/oui-dropdown/src/dropdown.controller.js
Preview: http://angular_oui_dropdown_min_width.ui-kit.ovh/#!/oui-angular/dropdown
=> fix(ouiDropdown): fix dropdown min width

CHANGELOG.md
=> doc(changelog): add previous and current versions changelog

packages/oui-back-button/src/back-button.controller.js, packages/oui-button/src/button.controller.js
=> fix(tests): fix button and back-button tests

packages/oui-datagrid/src/datagrid-column-builder.service.js, packages/oui-datagrid/src/datagrid.controller.js
=> fix(datagrid): add scope context to process header titles

package.json
=> feat(build): standard test script alias

packages/oui-checkbox/README.md, packages/oui-checkbox/src/checkbox.component.js, packages/oui-checkbox/src/checkbox.controller.js, packages/oui-checkbox/src/checkbox.html, packages/oui-checkbox/src/index.spec.js
=> feat(checkbox): add required attribute

packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/datagrid.html
=> Fix datagrid loading

packages/oui-navbar/src/navbar.html
Linked with https://github.com/ovh-ux/ovh-ui-kit/pull/142
=> fix(navbar): fix closing the notifications menu when clicked

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-modal/README.md, packages/oui-modal/src/index.js, packages/oui-modal/src/index.spec.js, packages/oui-modal/src/modal.component.js, packages/oui-modal/src/modal.html
https://github.com/ovh-ux/ovh-ui-kit/pull/137
=> feat(modal): add new component for modal

packages/oui-checkbox/src/index.spec.js, packages/oui-datagrid/src/index.spec.js, packages/oui-pagination/src/index.spec.js, packages/oui-radio/src/index.spec.js
=> chore(): fix eslint errors

packages/oui-field/src/index.spec.js, packages/oui-modal/src/index.spec.js
=> fix(): fix indentation

packages/oui-navbar/src/group/navbar-group.service.js, packages/oui-navbar/src/index.spec.data.json, packages/oui-navbar/src/menu/navbar-menu.controller.js, packages/oui-navbar/src/menu/navbar-menu.html, packages/oui-navbar/src/navbar.controller.js, packages/oui-navbar/src/navbar.html
UU-717
Add hierarchical navigation for internal menus
http://angular_style_navbar_aside_menus.ui-kit.ovh/#!/oui-angular/navbar
=> style(navbar): update template for internal menus

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-textarea/README.md, packages/oui-textarea/src/index.js, packages/oui-textarea/src/index.spec.js, packages/oui-textarea/src/textarea.component.js, packages/oui-textarea/src/textarea.controller.js, packages/oui-textarea/src/textarea.html, packages/oui-textarea/src/textarea.provider.js
=> feat(textarea): add new component

packages/oui-field/README.md, packages/oui-field/src/field.controller.js, packages/oui-field/src/field.html, packages/oui-field/src/field.provider.js, packages/oui-field/src/index.spec.js, packages/oui-select/README.md, packages/oui-select/src/index.js, packages/oui-select/src/index.spec.js, packages/oui-select/src/select.controller.js, packages/oui-select/src/select.directive.js, packages/oui-select/src/select.html, packages/oui-select/src/templates/match.html, packages/oui-select/src/ui-select.js
=> Oui field textarea

packages/oui-textarea/README.md, packages/oui-textarea/src/index.spec.js, packages/oui-textarea/src/textarea.component.js, packages/oui-textarea/src/textarea.html
=> feat(textarea): add rows attribute

packages/oui-navbar/src/index.spec.data.json, packages/oui-navbar/src/menu/navbar-menu.html
Hide the link to open the submenu if its `subLinks` property is empty
http://angular_feature_empty_navbar_menu.ui-kit.ovh/#!/oui-angular/navbar
=> style(navbar): hide empty sublinks

packages/oui-button/src/button.controller.js
Following @neolitec comments on PR https://github.com/ovh-ux/ovh-ui-angular/pull/104 I replaced checks with addBooleanParameter.
=> fix(ouiButton): use addBooleanParameter

packages/oui-modal/README.md
on the API part README.md : on-close was wrote instead of on-dismiss
=> fix(oui-modal): README error on-dismiss doc

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-form-actions/README.md, packages/oui-form-actions/src/form-actions.component.js, packages/oui-form-actions/src/form-actions.controller.js, packages/oui-form-actions/src/form-actions.html, packages/oui-form-actions/src/form-actions.provider.js, packages/oui-form-actions/src/index.js, packages/oui-form-actions/src/index.spec.js
form-actions is composed by two buttons : a submit and a cancel button.
=> Feat(form-actions) : create component

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-search/README.md, packages/oui-search/src/index.js, packages/oui-search/src/index.spec.js, packages/oui-search/src/search.component.js, packages/oui-search/src/search.controller.js, packages/oui-search/src/search.html
UU-568
http://build_oui_search.ui-kit.ovh/#!/oui-angular/search
Linked to
https://github.com/ovh-ux/ovh-ui-kit/pull/158
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/61
=> feat(oui-search): add oui-search component

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-criteria-container/src/criteria-container.component.js, packages/oui-criteria-container/src/criteria-container.controller.js, packages/oui-criteria-container/src/index.js, packages/oui-criteria-container/src/index.spec.js
**Merge this AFTER https://github.com/ovh-ux/ovh-ui-angular/pull/105.**
Only the criteria container is in this pull request. Not any link to datagrid here.
=> feat(criteria-container): add new component

.scriptsrc, CHANGELOG.md, CONTRIBUTING.md, commitlint.config.js, package.json, yarn.lock
note: commit messages scope need to be a component name, but is optional (based on folders)
=> chore: commitlint, commitizen and conventional-changelog integration

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-radio-toggle-group/README.md, packages/oui-radio-toggle-group/src/index.js, packages/oui-radio-toggle-group/src/index.spec.js, packages/oui-radio-toggle-group/src/radio-toggle-group.component.js, packages/oui-radio-toggle/README.md, packages/oui-radio/README.md, packages/oui-radio/src/radio.component.js, packages/oui-radio/src/radio.controller.js, packages/oui-radio/src/radio.html
Staging: https://ovh_ui_kit_documentation-feat_radio_toggle_staging.uxci.ovh/#!/oui-angular/radio-toggle
=> UU-779 feat(radio-toggle): create component

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-chips/README.md, packages/oui-chips/src/chips.component.js, packages/oui-chips/src/chips.controller.js, packages/oui-chips/src/chips.html, packages/oui-chips/src/index.js, packages/oui-chips/src/index.spec.data.json, packages/oui-chips/src/index.spec.js
UU-727
http://build_oui_chips.ui-kit.ovh/#!/oui-angular/chips
Related to:
https://github.com/ovh-ux/ovh-ui-kit/pull/166
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/69
=> feat(oui-chips): add oui-chips component

packages/oui-field/README.md, packages/oui-field/src/field.controller.js, packages/oui-field/src/field.html, packages/oui-field/src/index.spec.js, packages/oui-select/src/select.controller.js
Staging: https://ovh_ui_kit_documentation-fix_form_submit_staging.uxci.ovh/#!/oui-angular/field
=> fix(oui-field): show errors on submit

packages/oui-form-actions/README.md, packages/oui-form-actions/src/form-actions.component.js, packages/oui-form-actions/src/form-actions.html, packages/oui-form-actions/src/index.spec.js
=> feat(oui-form-actions): handle href for cancel button

packages/oui-back-button/README.md, packages/oui-back-button/src/back-button.component.js, packages/oui-back-button/src/back-button.controller.js, packages/oui-back-button/src/back-button.html, packages/oui-back-button/src/index.spec.js
=> feat(oui-back-button): add the possibility to handle href

package.json, packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.component.js, packages/oui-calendar/src/calendar.controller.js, packages/oui-calendar/src/calendar.html, packages/oui-calendar/src/calendar.provider.js, packages/oui-calendar/src/index.js, packages/oui-calendar/src/index.spec.js, yarn.lock
UU-562
http://build_oui_calendar.ui-kit.ovh/#!/oui-angular/calendar
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/172
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/77
=> feat(oui-calendar): add oui-calendar component

.babelrc, packages/common/component-utils.js, packages/oui-datagrid/src/datagrid-column-builder.service.js
Staging: http://angular_fix_datagrid_ie_10.ui-kit.ovh/#!/oui-angular/datagrid
=> fix(oui-datagrid): fix datagrid for IE10

package.json, packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.provider.js
https://github.com/ovh-ux/ovh-ui-kit/pull/177
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/78
=> chore(oui-calendar): disable flatpickr mobile mode

package.json, packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.component.js, packages/oui-calendar/src/calendar.controller.js, packages/oui-calendar/src/calendar.html, packages/oui-calendar/src/calendar.provider.js, packages/oui-calendar/src/index.spec.js, packages/oui-field/README.md, yarn.lock
UU-778
* Bump flatpickr to v4.4.4
* Update oui-field examples
http://build_oui_field_calendar.ui-kit.ovh/#!/oui-angular/calendar
http://build_oui_field_calendar.ui-kit.ovh/#!/oui-angular/field
**Linked to**
https://github.com/ovh-ux/ovh-ui-kit/pull/180
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/83
=> chore(oui-calendar): bump flatpickr version to v4.4.3

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-popover/README.md, packages/oui-popover/src/index.js, packages/oui-popover/src/index.spec.js, packages/oui-popover/src/popover-content.directive.js, packages/oui-popover/src/popover-content.html, packages/oui-popover/src/popover-trigger.directive.js, packages/oui-popover/src/popover.component.js, packages/oui-popover/src/popover.controller.js, packages/oui-popover/src/popover.html
=> feat(oui-popover): add new Popover component

packages/oui-radio/README.md, packages/oui-radio/src/index.spec.js, packages/oui-radio/src/radio.controller.js
Boolean parameter on "thumbnail" attribute was missing.
=> fix(oui-radio): boolean parameter missing on thumbnail attr

packages/oui-select/README.md, packages/oui-select/src/index.spec.js
Update oui-select API documentation
Add Events examples
Add `on-change` test
http://build_oui_select.ui-kit.ovh
Linked to : 
ovh-ux/ovh-ui-kit-documentation/pull/91
=> Update oui-select documentation

packages/oui-select/src/templates/select.html, packages/oui-select/src/ui-select.js
Demo: http://fix_oui_select_dropdown_width_staging.ui-kit.ovh/#!/oui-angular/select
=> fix(oui-select): fix dropdown min-width

packages/oui-stepper/README.md, packages/oui-stepper/src/index.spec.js, packages/oui-stepper/src/step-form/step-form.component.js, packages/oui-stepper/src/step-form/step-form.controller.js, packages/oui-stepper/src/step-form/step-form.html, packages/oui-stepper/src/stepper.component.js, packages/oui-stepper/src/stepper.controller.js, packages/oui-stepper/src/stepper.provider.js
http://angular_chore_stepper_linear.ui-kit.ovh/#!/oui-angular/stepper
- Remove linear attribute. Is default behaviour now for `oui-stepper`.
- Add attributes for cancel `oui-form-actions`.
=> chore(oui-stepper): remove linear and add cancel button

packages/oui-navbar/src/navbar.html
Must be merged after https://github.com/ovh-ux/ovh-angular-module-status/pull/9 and the updated cloud manager
=> style(oui-navbar): navbar header must be displayed on full browser

packages/oui-modal/README.md, packages/oui-modal/src/index.spec.js, packages/oui-modal/src/modal.component.js, packages/oui-modal/src/modal.html
add type attribute that allows to handle icon : info, warning, success ..etc
=> feat(oui-modal): add type attribute to handle icon modal

packages/oui-navbar/README.md, packages/oui-navbar/src/navbar.html
Linked to
https://github.com/ovh-ux/ovh-ui-kit/pull/207
https://github.com/ovh-ux/ovh-documentation-toolkit/pull/27
=> style(oui-navbar): add brand title

packages/oui-field/src/field.controller.js, packages/oui-field/src/field.html
Add support for [ui-validator](https://github.com/angular-ui/ui-validate). 
See #148.
=> feat(oui-field): add custom message support

packages/oui-tile/src/tile.controller.js, packages/oui-tile/src/tile.html
UK-40
Linked to 
https://github.com/ovh-ux/ovh-ui-kit/pull/235
=> fix(oui-tile): fix normalize for height sizing

packages/oui-field/src/field.html, packages/oui-popover/README.md, packages/oui-tile/src/definition/tile-definition.html, packages/oui-tile/src/index.spec.js
Linked to https://github.com/ovh-ux/ovh-ui-kit/pull/241
=> fix(oui-popover): update style to specs

packages/oui-tile/README.md, packages/oui-tile/src/button/tile-button.component.js, packages/oui-tile/src/button/tile-button.controller.js, packages/oui-tile/src/button/tile-button.html, packages/oui-tile/src/index.spec.js
http://build_tile_button_disabled.ui-kit.ovh/#!/oui-angular/tile
Linked to https://github.com/ovh-ux/ovh-ui-kit/pull/247
=> feat(oui-tile): add disabled on oui-tile-button

packages/oui-select-picker/README.md, packages/oui-select-picker/src/select-picker.html
(Following previously merged PR : https://github.com/ovh-ux/ovh-ui-angular/pull/269)
=> Feat/select picker/default light templates

packages/oui-chips/src/chips.controller.js, packages/oui-chips/src/chips.html, yarn.lock
Fix https://github.com/ovh-ux/ovh-ui-angular/issues/278
=> fix(oui-chips): fix item removal

packages/oui-criteria-adder/README.md, packages/oui-stepper/README.md
Add classname on `pre` tags in documentation
=> style: fix json output

packages/oui-select-picker/README.md, packages/oui-select-picker/src/select-picker.controller.js, packages/oui-select-picker/src/select-picker.html
* fix selectedValue on init
* fix `id` for accessibility
* update documentation
=> fix(oui-select-picker): fix selected value on init

packages/oui-select-picker/src/select-picker.controller.js
=> fix(oui-select-picker): fix click propagation on parent label

packages/oui-datagrid/src/datagrid.html, packages/oui-datagrid/src/index.spec.js
=> feat(oui-datagrid): add skeletons when loading data

packages/oui-pagination/README.md, packages/oui-pagination/src/pagination.controller.js, packages/oui-pagination/src/pagination.html
Close https://github.com/ovh-ux/ovh-ui-angular/issues/354
**Related to**
- https://github.com/ovh-ux/ovh-ui-kit/pull/342
- https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/183
=> fix(oui-pagination): add input search when huge amount of pages

packages/oui-collapsible/README.md, packages/oui-collapsible/src/collapsible.component.js, packages/oui-collapsible/src/collapsible.controller.js, packages/oui-collapsible/src/index.spec.js
On header click this now dispatch the toggle event to a function passed in attributes with true/false parameter that defines if the collapsible shows his contents or not.
Know the state of the collapsible on change
=> feat(oui-collapsible): add handler on toggle open-close event

packages/oui-tabs/src/item/tabs-item.html
Avoid submitting form.
1acb744 — fix(oui-tabs): add button type
/cc @jleveugle @frenautvh @antleblanc @marie-j @AxelPeter
=> fix(oui-tabs): add button type

packages/oui-navbar/src/menu/navbar-menu.html
Display complete menu title on hover
=> feat(oui-navbar): display full menu title on hover

packages/oui-guide-menu/src/guide-menu.html
=> feat(oui-guide-menu): use guides icon

packages/oui-datagrid/src/datagrid.controller.js
7c46033 - refactor(oui-datagrid): remove extra console.log
=> refactor(oui-datagrid): remove extra console.log

packages/oui-tabs/README.md, packages/oui-tabs/src/index.spec.js, packages/oui-tabs/src/item/tabs-item.controller.js, packages/oui-tabs/src/tabs.component.js, packages/oui-tabs/src/tabs.controller.js, packages/oui-tabs/src/tabs.html
d06498d — feat(oui-tabs): allow to select active tab item
=> feat(oui-tabs): allow to select active tab item

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/menu/navbar-menu.component.js, packages/oui-navbar/src/menu/navbar-menu.controller.js, packages/oui-navbar/src/menu/navbar-menu.html, packages/oui-navbar/src/navbar.html, packages/oui-navbar/src/toggler/navbar-toggler.component.js, packages/oui-navbar/src/toggler/navbar-toggler.html
* Add possibility to add custom content with header title in menus 
⚠️ BREAKING CHANGE
=> feat(oui-navbar): allow to have custom content in menu header

packages/oui-tabs/src/tabs.controller.js
c0b5d75 — fix(oui-tabs): select dynamically active tab
=> fix(oui-tabs): select dynamically active tab

packages/oui-stepper/README.md, packages/oui-stepper/src/step-form/step-form.controller.js
Allow to associate global action on step form submission
=> feat(oui-stepper): emit event on form submit

packages/oui-criteria/src/adder/criteria-adder.html
Fix field size to `medium` to avoid the dropdown menu having width change
=> fix(oui-criteria): fix fields size to medium

packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/index.spec.js, packages/oui-datagrid/src/paging/datagrid-paging-abstract.js
=> fix(oui-datagrid): allow no property on oui-column

packages/oui-dropdown/src/item/dropdown-item.html
fix #425 
Backport of ovh-ux/ovh-ui-kit#498
=> fix(oui-dropdown): display button when item has href and is disabled

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/menu/navbar-menu.component.js, packages/oui-navbar/src/menu/navbar-menu.html
Allow menu header to be a link
=> feat(oui-navbar): allow to pass link as menu header

packages/oui-criteria/README.md, packages/oui-criteria/src/adder/criteria-adder.html, packages/oui-criteria/src/adder/criteria-adder.provider.js
Add description for Filter. 
By default the wording will be "Filter"
=> feat(oui-criteria): add filter description

package.json, yarn.lock
f8ba148 — build(oui-calendar): limit flatpickr version
=> build(oui-calendar): limit flatpickr version

packages/oui-select-picker/src/index.spec.js, packages/oui-select-picker/src/select-picker.component.js, packages/oui-select-picker/src/select-picker.controller.js, packages/oui-select-picker/src/select-picker.html
Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>
=> feat(oui-select-picker): add tranclude slot for description

packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.controller.js
=> fix(oui-calendar): dynamic changes for min and max date

packages/oui-radio/README.md, packages/oui-radio/src/toggle-group/radio-toggle-group.component.js
=> feat(oui-radio-toggle-group): add column direction

packages/common/component-utils.js, packages/oui-collapsible/src/collapsible.controller.js, packages/oui-collapsible/src/collapsible.html
=> fix(oui-collapsible): add helper to remove html on heading

packages/oui-datagrid/src/paging/datagrid-paging-abstract.js
Related https://github.com/ovh-ux/ovh-ui-kit/issues/554
=> feat(oui-datagrid): always call row-loader

packages/oui-datagrid/README.md, packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/datagrid.directive.js, packages/oui-datagrid/src/datagrid.html, packages/oui-datagrid/src/datagrid.provider.js
add component support to refresh datagrid
MANAGER-4342
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
=> feat(oui-datagrid): refresh datagrid

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/menu/navbar-menu.component.js, packages/oui-navbar/src/menu/navbar-menu.controller.js, packages/oui-navbar/src/menu/navbar-menu.html, packages/oui-navbar/src/notification/navbar-notification.component.js, packages/oui-navbar/src/notification/navbar-notification.controller.js
- Add a `variant` attribute onto `oui-navbar-menu` and `oui-navbar-notification`
- Update documentation
- Update unit tests
related to: https://github.com/ovh-ux/ovh-ui-kit/pull/557
ref: UK-148
=> feat(oui-navbar): add variant attribute onto menus

packages/oui-select-picker/src/select-picker.component.js, packages/oui-select-picker/src/select-picker.html
Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>
Backport on V3 can be done after the acceptation of this changes.
Some changes from prettier has been done
=> feat(oui-select-picker): add transclusion for label

packages/oui-datagrid/src/datagrid.html, packages/oui-datagrid/src/datagrid.provider.js, packages/oui-datagrid/src/parameters/datagrid-parameters.html
- Add tooltip on datagrid parameters
- Remove untranslated text
ref. UK-153
=> feat(oui-datagrid): add tooltip on datagrid parameters
