ovh-ux/ovh-ui-angular

package.json
Previously on Windows `yarn karma` and `yarn karma:watch` could not be run because `$(npm bin)` could not be found, so karma wasn't run. 
I replaced `$(npm bin)` by `node_modules/karma/bin` and it seems to work find on Windows and Mac but I didn't tested it on Linux.
=> fix(build): can run karam and karma:watch on windows

package.json
Without this fix `ovh-ui-angular` for a specific `ovh-ui-kit` version and it can conflict with the `ovh-ui-kit-documentation` dependency version.
=> hotfix(build): ovh-ui-kit as peer dependencies

packages/oui-action-menu/src/action-menu-item.controller.js, packages/oui-action-menu/src/action-menu.controller.js, packages/oui-back-button/src/back-button.controller.js, packages/oui-back-button/src/index.spec.js, packages/oui-button/src/button.controller.js, packages/oui-button/src/index.spec.js, packages/oui-checkbox/src/checkbox.controller.js, packages/oui-numeric/src/numeric.controller.js, packages/oui-radio/src/radio.controller.js, packages/oui-tooltip/src/tooltip.controller.js
Unlike what was done for fixing removeAttr bug from what jQuery documentation said (https://github.com/ovh-ux/ovh-ui-angular/pull/50), jqLite doesn't support multiple attributes: https://docs.angularjs.org/api/ng/function/angular.element
So we have to call `.removeAttr()` for each attributes.
=> fix(*): fix removeAttr parameter for jqLite

packages/oui-datagrid/src/datagrid-column-builder.service.js
=> fix(datagrid): avoid sorting if property attribute is not set in oui-column

packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/paging/datagrid-local-paging.js, packages/oui-datagrid/src/paging/datagrid-paging-abstract.js, packages/oui-datagrid/src/paging/datagrid-paging.service.js
=> fix(datagrid): prevent useless calls to row-loader

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/navbar.component.js, packages/oui-navbar/src/navbar.controller.js, packages/oui-navbar/src/navbar.html
UU-714
Add an attribute dedicated for the responsive menu.
In this way, we can faster displaying the navbar.
Linked to https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/57
=> feat(navbar): add a toggler-links attribute

packages/oui-datagrid/src/datagrid-column-builder.service.js, packages/oui-datagrid/src/index.spec.js
=> fix(datagrid): prevent datagrid to render empty cell when template is only white spaces

packages/oui-select/README.md, packages/oui-select/src/index.spec.js, packages/oui-select/src/select.directive.js
In case of string list instead of objects list passing to your item. You won't be able to match object attribute. So, to handle this case match attribute has been turned to optional.
http://angular_fix_oui_select.ui-kit.ovh/#!/oui-angular/select
=> fix(select): make match optional (handle string list)

packages/oui-back-button/README.md, packages/oui-button/README.md, packages/oui-checkbox/README.md, packages/oui-datagrid/README.md, packages/oui-dropdown/README.md, packages/oui-form-actions/README.md, packages/oui-message/README.md, packages/oui-navbar/README.md, packages/oui-numeric/README.md, packages/oui-pagination/README.md, packages/oui-radio-group/README.md, packages/oui-radio/README.md, packages/oui-search/README.md, packages/oui-spinner/README.md, packages/oui-tooltip/README.md
Standardize section order
1. Usage with previews
2. Api
3.Configuration
Remove not useful html example, preview+api are sufficient
=> docs:standardize documentation

packages/oui-field/src/field.controller.js
It's a ugly fix, we should change the pattern to not be forced to hardcode all possibilities. To discuss after...
=> fix(oui-field): support validations prefixed with data-ng

packages/oui-form-actions/README.md, packages/oui-form-actions/src/form-actions.component.js, packages/oui-form-actions/src/form-actions.controller.js, packages/oui-form-actions/src/form-actions.html, packages/oui-form-actions/src/index.spec.js
Some forms don't a cancel boutton so it must be hidden. Guidelines
say that submit button is always enabled, so I've remove the
disabled argument.
Breaks oui-form-actions:disabled, submit function will be called
event if oui-form-actions have a disabled argument.
=> feat(oui-form-actions): hide cancel button and don't disable submit

packages/oui-form-actions/src/form-actions.controller.js, packages/oui-form-actions/src/index.js, packages/oui-form-actions/src/index.spec.js
rename formActions provider to formActionsConfiguration for uniformity
with other components
Breaks all provider for actions-provider would have to be renamed
=> fix(oui-form-actions): rename form-actions-provider

packages/common/component-utils.js, packages/oui-checkbox/src/checkbox.controller.js, packages/oui-checkbox/src/index.spec.js, packages/oui-criteria-adder/src/criteria-adder.controller.js, packages/oui-dropdown/src/dropdown.controller.js, packages/oui-popover/src/popover.controller.js, packages/oui-radio/README.md, packages/oui-radio/src/index.spec.js, packages/oui-radio/src/radio.controller.js, packages/oui-select-picker/src/index.spec.js, packages/oui-select-picker/src/select-picker.controller.js
Rename id attribute to be in camel case. 
If it contains "-" char,  it won't be handle by angular in order to set validation for forms and access input.
=> Fix id attribute for forms and input

packages/oui-datagrid/src/cell/cell.controller.js
Wait for row promise to be resolved before displaying row template.
For example :
```
<oui-column>
<span data-ng-if="$row.foo">Foo</span>
<span data-ng-if="!$row.foo">Bar</span>
</oui-column>
```
Will display "Bar" during on the fly row loading which is not intended (we expect cell to be left blank). This fix wait the promise to be resolved and then compile the cell template.
=> fix(oui-datagrid): wait row promise before displaying cell template

package.json, yarn.lock
https://github.com/flatpickr/flatpickr/releases/tag/v4.5.0
Resolves the logs `Error{}` when launching the unit tests
=> chore(oui-calendar): bump version of flatpickr to v4.5.0

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-collapsible/README.md, packages/oui-collapsible/src/collapsible.component.js, packages/oui-collapsible/src/collapsible.controller.js, packages/oui-collapsible/src/collapsible.html, packages/oui-collapsible/src/index.js, packages/oui-collapsible/src/index.spec.js
UU-836
Collapsible component added.
**Linked to**
https://github.com/ovh-ux/ovh-ui-kit/pull/197
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/94
=> feat(oui-collapsible): collapsible component addition

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-skeleton/README.md, packages/oui-skeleton/src/index.js, packages/oui-skeleton/src/index.spec.js, packages/oui-skeleton/src/skeleton.component.js, packages/oui-skeleton/src/skeleton.controller.js, packages/oui-skeleton/src/skeleton.html
add oui skeleton component
add examples and test case
cui skeleton to oui
JIRA: UU-845
=> feat: oui skeleton

packages/oui-action-menu/README.md, packages/oui-action-menu/src/action-menu-item-button.html
I was asked by CX to upgrade more parts of the manager to the new ui-kit style (see SCDC-439).
But I stumbled upon an issue when adapting a button to the `oui-action-menu-item` component.
The button is supposed to toggle an option between "enabled" and "disabled" states, and therefore changes its text to exhibit what's going to happen if the user clicks on it.
It was working fine with the old system but now that I migrated it to a `oui-action-menu-item`, the text is one-time binding, preventing the underlying change to appear, keeping the button in an "activated" state regardless of the real value.
So I switched to one-way `<` binding.
=> fix(oui-action-menu): disable one-time binding for the text attribute

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.data.json, packages/oui-navbar/src/navbar.html, packages/oui-navbar/src/navbar.provider.js
- show a message when no notification or when something went wong
- add incident level for notifiacation
=> feat(oui-navbar): add placeholder for notification

packages/oui-datagrid/README.md, packages/oui-datagrid/src/cell/cell.controller.js, packages/oui-datagrid/src/datagrid-column-builder.service.js, packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/datagrid.directive.js, packages/oui-datagrid/src/datagrid.html, packages/oui-datagrid/src/index.js, packages/oui-datagrid/src/index.spec.js, packages/oui-datagrid/src/parameters/datagrid-parameters.component.js, packages/oui-datagrid/src/parameters/datagrid-parameters.controller.js, packages/oui-datagrid/src/parameters/datagrid-parameters.html, packages/oui-datagrid/src/parameters/datagrid-parameters.spec.js
SCDC-744
PR Doc: https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/115
PR Style: https://github.com/ovh-ux/ovh-ui-kit/pull/214
Staging: http://feature_datagrid_customize_staging.ui-kit.ovh//#!/oui-angular/datagrid
=> feat(oui-datagrid): add datagrid customization

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-page-header/README.md, packages/oui-page-header/src/index.js, packages/oui-page-header/src/index.spec.js, packages/oui-page-header/src/page-header.component.js, packages/oui-page-header/src/page-header.controller.js, packages/oui-page-header/src/page-header.html
`/#!/oui-angular/page-header` @ `ovh_ui_kit_documentation-feat_page_header_staging`
**Linked to**
https://github.com/ovh-ux/ovh-ui-kit/pull/219
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/119
=> feat(oui-page-header): create page-header component

packages/oui-back-button/README.md, packages/oui-back-button/src/back-button.component.js, packages/oui-back-button/src/back-button.controller.js, packages/oui-back-button/src/back-button.html, packages/oui-back-button/src/index.spec.js, packages/oui-collapsible/README.md, packages/oui-collapsible/src/collapsible.component.js, packages/oui-collapsible/src/collapsible.html, packages/oui-collapsible/src/index.spec.js, packages/oui-modal/README.md, packages/oui-modal/src/index.spec.js, packages/oui-modal/src/modal.component.js, packages/oui-modal/src/modal.controller.js, packages/oui-modal/src/modal.html, packages/oui-slideshow/README.md, packages/oui-slideshow/src/index.spec.js, packages/oui-slideshow/src/slideshow-panel.component.js, packages/oui-slideshow/src/slideshow-panel.html
Change `title` attribute to `heading` of components whose its value define an heading instead of a tooltip. The purpose is to avoid using the same attribute name as existing attribute for a different use.
For components already released, I added a support to ease the switch. 
It concern `oui-back-button` and `oui-modal`.
`oui-select` has a `title` attribute, but it's well used. So no need of changing it.
=> fix: rename title attribute to heading

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-tile/README.md, packages/oui-tile/src/button/tile-button.component.js, packages/oui-tile/src/button/tile-button.controller.js, packages/oui-tile/src/button/tile-button.html, packages/oui-tile/src/definition/tile-definition.component.js, packages/oui-tile/src/definition/tile-definition.controller.js, packages/oui-tile/src/definition/tile-definition.html, packages/oui-tile/src/index.js, packages/oui-tile/src/index.spec.js, packages/oui-tile/src/tile.component.js, packages/oui-tile/src/tile.controller.js, packages/oui-tile/src/tile.html
UK-5
tile
tile-button
tile-definition
test
=> feat(oui-tile): create component

packages/oui-datagrid/README.md, packages/oui-datagrid/src/datagrid-column-builder.service.js
=> fix(oui-datagrid): fix type options with dynamic columns

packages/oui-tile/README.md, packages/oui-tile/src/tile.html
Fix the loading attribute of `oui-tile`
http://angular_fix_loading_state.ui-kit.ovh/#!/oui-angular/tile
Linked to
https://github.com/ovh-ux/ovh-ui-kit/pull/232
=> fix(oui-tile): fix loading state

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-field/README.md, packages/oui-switch/README.md, packages/oui-switch/src/index.js, packages/oui-switch/src/index.spec.js, packages/oui-switch/src/switch.component.js, packages/oui-switch/src/switch.controller.js, packages/oui-switch/src/switch.html
/#!/ovh-ui-angular/switch @ ovh_ui_kit_documentation-feat_oui_switch_staging
Linked to
https://github.com/ovh-ux/ovh-ui-kit/pull/211
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/125
=> feat(oui-switch): add new oui-switch component

packages/oui-criteria-adder/src/criteria-adder.controller.js, packages/oui-criteria-adder/src/criteria-adder.html
hotfix : 
- fix dropdown closed when select input was clicked ...
- fix options not displayed when only one field is filterable
=> hotfix(oui-criteria-adder)

packages/oui-action-menu/src/action-menu.component.js
Before : You could only put `disabled` attribute on `oui-action-menu` in a static way
Now: `disabled` attribute accept dynamic values
=> fix(oui-action-menu): allow to disable action menu dynamically

packages/oui-tile/README.md, packages/oui-tile/src/button/tile-button.component.js, packages/oui-tile/src/button/tile-button.controller.js, packages/oui-tile/src/button/tile-button.html, packages/oui-tile/src/index.spec.js
Allow use of external link to open link in new tab, display external link icon
(Need merge of https://github.com/ovh-ux/ovh-ui-kit/pull/243 on ovh-ui-kit to be functional)
=> feat(oui-tile): add external link handle

packages/oui-datagrid/README.md, packages/oui-datagrid/src/cell/cell.component.js, packages/oui-datagrid/src/cell/cell.controller.js, packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/datagrid.directive.js, packages/oui-datagrid/src/datagrid.html, packages/oui-datagrid/src/extra-top/extra-top.component.js, packages/oui-datagrid/src/extra-top/extra-top.controller.js, packages/oui-datagrid/src/index.spec.js
=> feat(oui-datagrid): add selectable rows

.github/CODEOWNERS
58cdeb9 - fix: use the right codeowners syntax
/cc @jleveugle @Jisay @frenautvh @cbourgois
=> fix: use the right codeowners syntax

packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.component.js, packages/oui-calendar/src/calendar.controller.js
Add to the component the enableTime option to display a time picker if needed.
See enableTime option of flatpickr for more information: https://flatpickr.js.org/options/
=> feat(oui-calendar): add enableTime option

packages/oui-message/README.md, packages/oui-message/src/message.component.js, packages/oui-message/src/message.controller.js, packages/oui-message/src/message.html
http://angular_feature_closable_message.ui-kit.ovh/#!/oui-angular/message
* Add an attribute to force the dismissable state
=> feat(oui-message): add dismissable attribute

package.json, packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/toggler/navbar-toggler.component.js, packages/oui-navbar/src/toggler/navbar-toggler.controller.js, packages/oui-navbar/src/toggler/navbar-toggler.html, yarn.lock
- Add `on-click` attribute
- Add `active` flag
- Add `loading` flag
- Add unit tests
=> feat(oui-navbar): add onclick and manual control on toggler

packages/oui-select-picker/src/select-picker.component.js, packages/oui-select-picker/src/select-picker.controller.js
(Related to https://github.com/ovh-ux/ovh-ui-kit/pull/275)
=> feat(oui-select-picker): add default light templates

packages/oui-select-picker/src/select-picker.controller.js, packages/oui-select-picker/src/select-picker.html
* Apply main classname on component instead of a child tag
=> fix(oui-select-picker): fix main classname on component

packages/oui-select/README.md, packages/oui-select/src/index.spec.js, packages/oui-select/src/select.directive.js, packages/oui-select/src/select.html, packages/oui-select/src/templates/choices.html
=> feat(oui-select): allow items to be disabled

packages/oui-navbar/src/navbar.html
If main links was done with attribute `main-links`, it doesn't supported the states. Only the href/url property.  This fix will resolve the problem.
=> fix(oui-navbar): fix state attributes on component links

packages/oui-datagrid/README.md, packages/oui-datagrid/src/cell/cell.controller.js, packages/oui-datagrid/src/index.spec.js
Before: it was not possible to use row index value 
Now: Row index can be accessed with `$rowIndex`
=> feat(oui-datagrid): permit to access row index

packages/oui-select-picker/src/index.spec.js, packages/oui-select-picker/src/select-picker.html
If there was no `match` attribute set and a section was added, an empty section was created 
Also, if no `match` attribute, `select` displayed empty values
=> fix(oui-select-picker): prevent leaving blank space

packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.controller.js
UK-66
* Add enable-time example
* Fix boolean parameters `enable-time` and `static`
Related to https://github.com/ovh-ux/ovh-ui-kit/pull/301
=>  fix(oui-calendar): fix boolean parameters 

packages/oui-select/src/select.html
When option is clicked form validation is triggered which cause the element to go in error status for a small instant
Prevent form validation if select is open 
Example can be found : 
MANAGER-1840
=> fix(oui-select): prevent required validation to trigger on select

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-inline-adder/README.md, packages/oui-inline-adder/src/field/inline-adder-field.component.js, packages/oui-inline-adder/src/field/inline-adder-field.controller.js, packages/oui-inline-adder/src/index.js, packages/oui-inline-adder/src/index.spec.js, packages/oui-inline-adder/src/inline-adder.component.js, packages/oui-inline-adder/src/inline-adder.controller.js, packages/oui-inline-adder/src/inline-adder.html, packages/oui-inline-adder/src/inline-adder.provider.js, packages/oui-inline-adder/src/row/inline-adder-row.component.js
UK-16
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/302
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/168
=> feat(oui-inline-adder): add inline-adder component

packages/oui-navbar/README.md, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/link/navbar-link.component.js, packages/oui-navbar/src/link/navbar-link.html, packages/oui-navbar/src/menu/navbar-menu.html, packages/oui-navbar/src/navbar.html
Before: if sublink was a link it was not possible to associate custom action on click
Now: action can be executed on link click
=> feat(oui-navbar): allow actions on navbar menu links

packages/oui-dropdown/src/index.spec.js, packages/oui-dropdown/src/item/dropdown-item.html
Before : `on-click` callback was not available for element with `state` or `href`
Now: `on-click` callback is available for all `oui-dropdown-item` (and therefore `oui-action-menu-item`)
=> feat(oui-dropdown): allow click on link items

packages/oui-navbar/README.md, packages/oui-navbar/src/dropdown/navbar-dropdown.component.js, packages/oui-navbar/src/dropdown/navbar-dropdown.html, packages/oui-navbar/src/index.spec.data.json, packages/oui-navbar/src/index.spec.js, packages/oui-navbar/src/navbar.html
Allow Aside link menu icon to have a shaking animation
=> feat(oui-navbar): allow to animate icon on aside links

packages/oui-modal/README.md, packages/oui-modal/src/index.spec.js, packages/oui-modal/src/modal.component.js, packages/oui-modal/src/modal.controller.js, packages/oui-modal/src/modal.html
Add `primary-disabled` and `secondary-disabled` attributes to `<oui-modal>`.
=> feat(oui-modal): allow disabling oui-modal buttons

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-dual-list/README.md, packages/oui-dual-list/package.json, packages/oui-dual-list/src/dual-list.component.js, packages/oui-dual-list/src/dual-list.controller.js, packages/oui-dual-list/src/dual-list.provider.js, packages/oui-dual-list/src/index.js, packages/oui-dual-list/src/index.spec.data.json, packages/oui-dual-list/src/index.spec.js, packages/oui-dual-list/src/source/dual-list-source.component.js, packages/oui-dual-list/src/source/dual-list-source.controller.js, packages/oui-dual-list/src/source/dual-list-source.html, packages/oui-dual-list/src/target/dual-list-target.component.js, packages/oui-dual-list/src/target/dual-list-target.controller.js, packages/oui-dual-list/src/target/dual-list-target.html, packages/oui-inline-adder/package.json, packages/oui-inline-adder/src/inline-adder.html, packages/oui-inline-adder/src/inline-adder.provider.js, packages/oui-navbar/src/navbar.provider.js, packages/oui-pagination/src/pagination.html, packages/oui-search/src/search.html
UK-15
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/307
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/171
=> feat(oui-dual-list): add dual-list component

packages/oui-select-picker/README.md, packages/oui-select-picker/src/index.js, packages/oui-select-picker/src/section/select-picker-section.component.js, packages/oui-select-picker/src/select-picker.component.js, packages/oui-select-picker/src/select-picker.controller.js, packages/oui-select-picker/src/select-picker.html
UK-57
* Add transclude with `oui-select-picker-section` instead of targeting `span` 
* Add deprecated support
=> fix(oui-select-picker): fix transclude with component instead of span

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-tabs/README.md, packages/oui-tabs/package.json, packages/oui-tabs/src/index.js, packages/oui-tabs/src/index.spec.js, packages/oui-tabs/src/item/tabs-item.component.js, packages/oui-tabs/src/item/tabs-item.controller.js, packages/oui-tabs/src/item/tabs-item.html, packages/oui-tabs/src/tabs.component.js, packages/oui-tabs/src/tabs.controller.js, packages/oui-tabs/src/tabs.html
UK-62
Related to
* https://github.com/ovh-ux/ovh-ui-kit/pull/311
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/173
=> feat(oui-tabs): add tabs component

packages/oui-angular/src/index.js, packages/oui-angular/src/index.spec.js, packages/oui-field/src/field.html, packages/oui-field/src/field.provider.js, packages/oui-file/README.md, packages/oui-file/package.json, packages/oui-file/src/file.component.js, packages/oui-file/src/file.controller.js, packages/oui-file/src/file.html, packages/oui-file/src/file.provider.js, packages/oui-file/src/index.js, packages/oui-file/src/index.spec.js
UK-60
Related to
* https://github.com/ovh-ux/ovh-ui-kit/pull/312
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/174
=> feat(oui-file): add file component

packages/oui-select/src/select.controller.js, packages/oui-select/src/templates/match.html
support nested property like "region.name" on match input in oui-select component
Closes #MANAGER-2056
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
support nested property like "region.name" on match input in oui-select component
oui-select-picker uses oui-select. This issue happens If match property has nested properties like 'region.name.' The reason is that of a bug in match.html used by oui-select. It does not take the nested property into consideration.
```
<span class="ui-select-match-text"
ng-hide="$select.isEmpty()"
ng-bind-html="$select.selected[$ctrl.match] || $select.selected">
</span> …
```
=> fix(oui-select): nested property support for match api

packages/oui-slideshow/src/slideshow.controller.js
Fix UK-84:
`ReferenceError: "event is not defined"` console error
=> fix(oui-slideshow): fix onDismiss callback

packages/oui-angular/src/index.js, packages/oui-calendar/README.md, packages/oui-calendar/src/calendar.controller.js, packages/oui-calendar/src/calendar.html, packages/oui-calendar/src/index.spec.js, packages/oui-timepicker/README.md, packages/oui-timepicker/package.json, packages/oui-timepicker/src/index.js, packages/oui-timepicker/src/index.spec.js, packages/oui-timepicker/src/timepicker.component.js, packages/oui-timepicker/src/timepicker.controller.js, packages/oui-timepicker/src/timepicker.html, packages/oui-timepicker/tests/index.js
UK-61
Related to:
* https://github.com/ovh-ux/ovh-ui-kit/pull/327
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/179
=> feat(oui-timepicker): add timepicker component

packages/oui-dropdown/src/dropdown.controller.js
Hello,
Currently, if you have a dropdown inside a DOM element with a `position: absolute`, the dropdown will pop at the wrong place.
Default parameter of Popper.js fix the issue.
Dropdown will now display correctly in that case
I can't reproduce an issue, which explains why we choose to override some modifiers. 
It is possible that in other cases, it is broken. However, we use the default behavior of Popper.js, so the risk is minimal I think.
Internal use: OM-266
=> fix(oui-dropdown): fix dropdown menu positioning

packages/oui-criteria/README.md
2e9022a — docs(oui-criteria): typo on basic example usage
=> docs(oui-criteria): typo on basic example usage

packages/oui-file/src/file.html, packages/oui-file/src/index.spec.js
Since [AngularJS 1.7.6](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#176-gravity-manipulation-2019-01-17), there is an error when using `input[hidden]` in oui-file.
To avoid this, the `input[hidden]` has been changed to `input[text]`, hidden using CSS.
=> fix(oui-file): fix input hidden error from ng 1.7.6

packages/oui-guide-menu/README.md, packages/oui-page-header/README.md
91e2ace — docs(oui-page-header): remove typo in example
4562036 — docs(oui-guide-menu): remove typo in example
/cc @AxelPeter @FredericEspiau
=> docs(oui-page-header): remove typo in example

packages/oui-criteria/src/adder/criteria-adder.html, packages/oui-dropdown/src/dropdown.controller.js, packages/oui-popover/src/popover.controller.js
Fix MBP-294
Set back the modifiers removed from https://github.com/ovh-ux/ovh-ui-angular/pull/349
In the same time, the value of the modifiers has been changed to target the viewport.
=> fix: fix popper.js modifiers

packages/oui-popover/README.md, packages/oui-popover/src/index.spec.js, packages/oui-popover/src/popover.controller.js, packages/oui-popover/src/popover.directive.js
* Add the possibility to extend the isolated scope create for the popover's template.
* Update documentation
* Update unit tests
=> feat(oui-popover): add scope attribute for template

packages/oui-slideshow/README.md, packages/oui-slideshow/src/index.spec.js, packages/oui-slideshow/src/slideshow.component.js, packages/oui-slideshow/src/slideshow.controller.js
add on-click event for slideshow navigation
add test case and example
More options
None
Helps resolve MBE-283
=> feat(oui-slideshow): add on click event for navigation

packages/oui-modal/src/modal.html
504a1dd — fix(oui-modal): hide content when loading
/cc @AxelPeter @jleveugle @marie-j
=> fix(oui-modal): hide content when loading

packages/oui-stepper/src/step-form/step-form.controller.js
Custome validation is stepper component
Use case: Execute costume validation on submitting a stepper and do not go to the next step if the validation fails.
The only way to achieve this is to use the valid method of the stepper component. I have added my custom validation in a valid method but this method gets executed many many times which is not very efficient and taking longer time. I want to execute (only once) complex validation on form submit and go to the next step only if the validation succeeds. 
<oui-step-form data-header="Size the nodes"
data-loading="$ctrl.supportedFlavors.loading && $ctrl.quota.loading"
data-on-focus="$ctrl.initNodes()"
data-valid="$ctrl.isNodesValid()"
data-on-submit="$ctrl.submitNodesInformation()">
<div data-ng-include="'adp/deploy/nodes.html'"></div> …
=> fix(oui-stepper): conditional step navigation

packages/oui-select-picker/src/select-picker.controller.js
c1f51a0 — fix(oui-select-picker): update when model changes
/cc @jleveugle @frenautvh @antleblanc @marie-j @AxelPeter
=> fix(oui-select-picker): update when model changes

packages/oui-stepper/README.md, packages/oui-stepper/src/index.spec.js, packages/oui-stepper/src/step-form/step-form.component.js, packages/oui-stepper/src/step-form/step-form.controller.js, packages/oui-stepper/src/step-form/step-form.html
By default, after validating a step, user can edit it and update his choice.
```html
<oui-step-form header="Simple step" description="This is a description">
```
we want to let our developpers decide when this update is possible. Today, user can do it as he wishes, this can be problematic in case of loading for example.
Example:
```html
<oui-step-form header="Simple step" description="This is a description" editable="false">
```
will result by removing the link: "Modifying this step"
=> feat(oui-stepper): add new attribute (editable)

packages/oui-popover/README.md, packages/oui-popover/src/index.spec.js, packages/oui-popover/src/popover.controller.js, packages/oui-popover/src/popover.directive.js
* allow to control popover open state with `open` attribute
* add `on-open` and `on-close` triggers
ceaa68d — feat(oui-popover): add open, on-open and on-close bindings
/cc @jleveugle @marie-j @AxelPeter
=> feat(oui-popover): add open, on-open and on-close bindings

packages/oui-datagrid/README.md, packages/oui-datagrid/src/datagrid.controller.js, packages/oui-datagrid/src/datagrid.directive.js, packages/oui-datagrid/src/datagrid.service.js, packages/oui-datagrid/src/index.spec.js
Prevent automatic scrolling on pagination change 
Avoid unexpected side effects with component integration 
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/192
=> fix(oui-datagrid): prevent pagination change from scrolling the view

packages/oui-stepper/README.md, packages/oui-stepper/src/index.spec.js, packages/oui-stepper/src/stepper.component.js, packages/oui-stepper/src/stepper.controller.js
Add `currentIndex` as binding to be able to set open state
To be able to switch between steps without user action
=> feat(oui-stepper): add ability to set open step

packages/oui-field/src/field.controller.js, packages/oui-password/README.md, packages/oui-password/src/index.spec.js, packages/oui-password/src/password.component.js, packages/oui-password/src/password.controller.js
Trigger for validation in cases where the validation depends on other controls. This can be used, for example in confirm password field, where the filed depends on the actual password
Staging: https://ovh_ui_kit_documentation_new-feat_password_validation_trigger.uxci.ovh
=> feat(oui-password): validation trigger

packages/oui-clipboard/src/clipboard.html
Avoid to submit form when a `oui-clipboard` element is present in a form.
28ab699 — fix(oui-clipboard): set button type
=> fix(oui-clipboard): set button type

packages/oui-action-menu/README.md, packages/oui-dropdown/README.md, packages/oui-dropdown/src/dropdown.controller.js, packages/oui-dropdown/src/index.spec.js
Add `placement` parameter to be able to open menu when it's wanted 
If a menu is quite large, this can help to find best placement especially for responsive
=> feat: allow to pass placement to oui-action-menu

packages/oui-form-actions/README.md, packages/oui-form-actions/src/form-actions.component.js, packages/oui-form-actions/src/form-actions.controller.js, packages/oui-form-actions/src/form-actions.html, packages/oui-form-actions/src/index.spec.js
Add possibility to pass a `disabled` parameter to disable submit button
=> feat(oui-form-actions): allow submit button to be disabled

packages/oui-dropdown/src/dropdown.controller.js
'x-arrow' was not set when no `start` or `end` was specified
=> fix(oui-dropdown): fix automatic center positionning

packages/oui-select/src/select.controller.js
The method "hideErrors" doesn't exists anymore in oui-field controller
=> fix(oui-select): remove invalid hideErrors method call

packages/oui-dropdown/src/dropdown.controller.js
Prevent Popper from opening dropdown another way that specified
=> fix(oui-dropdown): prevent popper from changing the placement

packages/oui-stepper/src/step-form/step-form.html
Show the 'modify step' button even when the previous steps aren't submitted.
=> fix(oui-stepper): fix modify step button appearance

packages/oui-tile/README.md, packages/oui-tile/src/definition/tile-definition.component.js, packages/oui-tile/src/definition/tile-definition.controller.js, packages/oui-tile/src/definition/tile-definition.html, packages/oui-tile/src/index.spec.js
- add transclude `<oui-tile-term>`
- add transclude `<oui-tile-actions>`
- update stories
- update documentation
- update unit tests
Allow to add custom tags, to facilitate the migration.
For example:
```html
<div class="oui-tile__item">
<dl class="oui-tile__definition">
<dt class="oui-tile__term">
<service-expiration-label></service-expiration-label>
</dt>
<dd class="oui-tile__description">
<service-expiration-date></service-expiration-date>
</dd>
</dl>
<div class="oui-tile__actions">
<service-expiration-date></service-expiration-date>
</div>
</div>
```
=> feat(oui-tile): add transclude for term and actions

packages/oui-criteria/README.md, packages/oui-criteria/src/adder/criteria-adder.html, packages/oui-criteria/src/adder/criteria-adder.spec.data.json, packages/oui-criteria/src/adder/criteria-adder.spec.js
Backport from https://github.com/ovh-ux/ovh-ui-kit/pull/476
- Add support of `hideOperators` property
- Update unit tests
- Update documentation
=> feat(oui-criteria): add ability to hide operators field

packages/oui-numeric/src/index.spec.js, packages/oui-numeric/src/numeric.controller.js, packages/oui-numeric/src/numeric.html
Allow OUI numeric value to be changed using keyboard
Value in OUI numeric can be changed/removed/deleted using keyboard
Showing error if value is empty, less than min or more than max
Changed and added new test cases
Its possible to update numeric value using keyboard always
none
MBP-505
=> fix(oui-numeric): keyboard support to change value

packages/oui-datagrid/src/datagrid-column-builder.service.js, packages/oui-datagrid/src/datagrid.controller.js
Allow to use attributes from `oui-datagrid-column` and properties from `column` attribute, and not one or another.
Property value from the `column` attribute has the preference if both are set.
=> fix(oui-datagrid): allow columns configuration from attribute and tag

packages/oui-numeric/src/index.spec.js, packages/oui-numeric/src/numeric.controller.js
75cb6a4 — fix(oui-numeric): allow custom min and max values
=> fix(oui-numeric): allow custom min and max values

packages/oui-header-tabs/src/header-tabs-item.controller.js
In some cases, the use of `replaceWith` cause duplication when associated with a `ngRepeat`.
It has no other purpose than keeping the same HTML structure as the style example [here](https://ovh-ux.github.io/ovh-ui-kit-documentation/#!/ovh-ui-kit/header-tabs).
The style has been updated in another PR: https://github.com/ovh-ux/ovh-ui-kit/pull/523
=> fix(oui-header-tabs): remove replaceWith that cause item duplication

packages/oui-dropdown/src/trigger/dropdown-trigger.controller.js
fix(oui-dropdown): afterClose should remove the focus
Focus of the element is correctly removed by using [`.blur()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur).
None.
None.
- No quality check required.
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
=> fix(oui-dropdown): afterClose should remove the focus

packages/oui-datagrid/src/util.js
This allow to also use getters as properties
fixes #448
=> fix(oui-datagrid): use lodash get to check properties

packages/oui-select/src/index.spec.js, packages/oui-select/src/select.controller.js, packages/oui-select/src/select.html
trigger `onChange` callback when element from multiple selection is removed
Allow to watch changes on element removal
None 
No issue was created for this matter
=> fix(oui-select): trigger onChange when element is removed
